# Generated by Django 4.0.4 on 2022-04-20 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autobuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobus',
            name='fecha_salida',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autobus',
            name='hora_salida',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
