# Generated by Django 4.0.4 on 2022-04-20 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autobuses', '0002_autobus_fecha_salida_autobus_hora_salida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autobus',
            old_name='Chofer',
            new_name='chofer',
        ),
    ]
