# Generated by Django 4.0.4 on 2022-04-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autobuses', '0003_rename_chofer_autobus_chofer'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobus',
            name='procentajeDePasajeros',
            field=models.CharField(default=0, max_length=3, verbose_name='Porcentaje de pasajeros por autobus'),
            preserve_default=False,
        ),
    ]
