# Generated by Django 4.0.4 on 2022-04-20 01:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trayectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trayecto',
            name='fecha_hora_salida',
        ),
        migrations.AddField(
            model_name='trayecto',
            name='fecha_salida',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trayecto',
            name='hora_salida',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
