# Generated by Django 4.0.4 on 2022-04-20 23:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autobuses', '0003_rename_chofer_autobus_chofer'),
        ('pasajeros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='autobus',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='autobuses.autobus', verbose_name='Autobus asignado'),
            preserve_default=False,
        ),
    ]
